name: project_structure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2


# Automatically upgrade your package to the latest versions: `flutter pub upgrade --major-versions`
# Check dependencies have newer versions available: `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.1
  package_info_plus: ^8.2.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  store_redirect: ^2.0.3
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  flutter_gen: ^5.9.0
  retrofit_generator: ^9.1.7
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^11.3.0
  dropdown_button2: ^2.3.9
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800


flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      directory_path_enabled: true